version: '3.9'

services:
  order_backend:
    build: .
    # build:
    #   dockerfile: Dockerfile.local
    #   context: .
    #   target: dev
    container_name: order_backend
    ports:
      - 4002:4000
    volumes:
      - .:/app
    depends_on:
      - order_database
      # -orders  
    networks:
      - order
      # - user

  order_database:
    image: 'mariadb:10.1.24'
    container_name: order_database
    restart: always
    # ports:
    #   - 33067:3306 
    environment:
       MYSQL_DATABASE: order
       MYSQL_ROOT_PASSWORD: Johnanthom@7
    volumes:
      - .dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - order


networks:
  # user:
  #   external:
  #     name: user
  order:
